version: 2.1
jobs:
   build:
     working_directory: ~/happyfoxinc/workflows-web
     docker:
       - image: circleci/node:lts-stretch
         environment:
           CHROME_BIN: "/usr/bin/google-chrome"
           JOBS: 1
     steps:
       - checkout
       - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "yarn.lock" }}
            - v4-dependencies-
       - run:
           name: Yarn Install
           command: yarn install --ignore-engines
       - save_cache:
           key: v4-dependencies-{{ checksum "yarn.lock" }}
           paths:
             - "~/.cache/yarn"
             - "node_modules"
             - "yarn.lock"